<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import Icon from "../components/common/Icon.vue";
import { consoleNavGroups, consoleStats } from "../mocks/console";
import { apiJson, ApiError, jsonBody, requestApi, readApiPayload } from "../lib/api";
import { clearAuthSession, getAuthSession, getInitials, roleLabel } from "../lib/session";
import type { BackendUser } from "../lib/session";
import type { ConsoleNavItem } from "../types";

interface AdminUser { id: number; username: string; bio?: string; role: number; disabled: boolean; stuname?: string; stuid?: string; verified?: boolean; }
interface ApiPost { id: number; text: string; timestamp: number; reply: number; likenum: number; follownum: number; username: string; userid: number; tags?: string[]; }
interface AdminComment { cid: number; pid: number; text: string; timestamp: number; username: string; userid: number; likenum: number; }
interface TableInfo { exists: boolean; rows: number; model?: string; description?: string; columns?: string[]; }
interface TablePayload { table: string; columns: string[]; types: string[]; count: number; data: Array<Record<string, unknown>>; }
interface WechatArticle { id: number; title: string; description: string; mp_name: string; url: string; publish_time: string; tag: string; }
interface Report { id: number; post_id?: number; comment_id?: number; reason?: string; status?: string; [key: string]: unknown; }

const props = withDefaults(defineProps<{ initialPath?: string }>(), { initialPath: "/console" });
const currentPath = ref(props.initialPath || "/console");
const currentUser = ref<BackendUser | null>(null);
const sidebarOpen = ref(false);
const collapsedGroups = ref<Record<string, boolean>>({});
const paletteOpen = ref(false);
const paletteQuery = ref("");
const designerOpen = ref(false);
const paletteInput = ref<HTMLInputElement>();
const toast = ref("");
const busy = ref(false);

const users = ref<AdminUser[]>([]);
const posts = ref<ApiPost[]>([]);
const articles = ref<WechatArticle[]>([]);
const comments = ref<AdminComment[]>([]);
const selectedCommentPostId = ref<number | null>(null);
const reports = ref<Report[]>([]);
const tables = ref<Array<{ name: string; info: TableInfo }>>([]);
const selectedTable = ref("");
const tableData = ref<TablePayload | null>(null);
const tableJson = ref("[]");
const migration = ref<string[]>([]);
const migrationState = ref("尚未检查数据库迁移状态");
const createUsername = ref("");
const createPassword = ref("");
const createRole = ref(0);
const wechatStatus = ref<"unknown" | "valid" | "expired" | "checking">("unknown");
const wechatExpiry = ref<number | null>(null);
const wechatArticles = ref<WechatArticle[]>([]);
const qrcodeUrl = ref("");
const wechatMessage = ref("");

const allItems = computed(() => consoleNavGroups.flatMap((group) => group.items));
const currentItem = computed<ConsoleNavItem>(() => allItems.value.find((item) => item.path === currentPath.value) ?? allItems.value[0]);
const paletteItems = computed(() => allItems.value.filter((item) => `${item.label} ${item.path}`.toLowerCase().includes(paletteQuery.value.toLowerCase())));
const tableRows = computed(() => tableData.value?.data ?? []);
const selectedCommentPost = computed(() => posts.value.find((post) => post.id === selectedCommentPostId.value));

let toastTimer: number | undefined;
let qrPollTimer: number | undefined;
const showToast = (message: string) => { toast.value = message; window.clearTimeout(toastTimer); toastTimer = window.setTimeout(() => { toast.value = ""; }, 2600); };
const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : "请求失败，请稍后重试。";
const handleError = (error: unknown) => { if (error instanceof ApiError && error.status === 401) { clearAuthSession(); window.location.assign(`/login?next=${encodeURIComponent(window.location.pathname)}`); return; } showToast(errorMessage(error)); };
const displayTime = (timestamp: number) => new Date(timestamp * 1000).toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" });
const displayCell = (value: unknown) => value === null || value === undefined ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value);
const groupKey = (label: string | undefined, index: number) => label || `group-${index}`;

const navigate = (path: string) => { currentPath.value = path; sidebarOpen.value = false; window.history.pushState({}, "", path); void loadPage(path); };
const toggleGroup = (key: string) => { collapsedGroups.value[key] = !collapsedGroups.value[key]; };
const openPalette = () => { paletteOpen.value = true; nextTick(() => paletteInput.value?.focus()); };
const closePalette = () => { paletteOpen.value = false; paletteQuery.value = ""; };
const onKeydown = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); openPalette(); } if (event.key === "Escape") { closePalette(); designerOpen.value = false; sidebarOpen.value = false; } };
const onPopstate = () => { currentPath.value = window.location.pathname; void loadPage(currentPath.value); };

const loadUsers = async () => { users.value = ((await apiJson<{ users: AdminUser[] }>("/users")).data?.users || []); };
const loadPosts = async () => { posts.value = (await apiJson<ApiPost[]>("/forum/posts?limit=100&begin=0")).data || []; };
const loadArticles = async () => { articles.value = (await apiJson<WechatArticle[]>("/wechat/posts?limit=100&page=1")).data || []; };
const loadComments = async () => { if (selectedCommentPostId.value === null) { comments.value = []; return; } comments.value = (await apiJson<AdminComment[]>(`/forum/comments/${selectedCommentPostId.value}?limit=100&begin=0&sort=asc`)).data || []; };
const loadReports = async () => { reports.value = (await apiJson<Report[]>("/admin/forum/reports")).data || []; };
const loadTables = async () => { const result = (await apiJson<Record<string, TableInfo>>("/dba/db-tables")).data || {}; tables.value = Object.entries(result).map(([name, info]) => ({ name, info })).sort((a, b) => a.name.localeCompare(b.name)); if (!selectedTable.value && tables.value.length) await selectTable(tables.value[0].name); };
const selectTable = async (name: string) => { selectedTable.value = name; try { const result = await apiJson<TablePayload>(`/dba/db-tables/${encodeURIComponent(name)}`); tableData.value = result.data; tableJson.value = JSON.stringify(result.data.data || [], null, 2); } catch (error) { handleError(error); } };
const checkMigration = async () => { try { const result = await apiJson<{ migration: string[] }>("/dba/db-tables/migrate"); migration.value = result.data?.migration || []; migrationState.value = `检查完成，共 ${migration.value.length} 条结果`; } catch (error) { handleError(error); } };
const executeMigration = async () => { if (!window.confirm("确认执行数据库迁移？这会修改测试数据库结构。")) return; try { await apiJson("/dba/db-tables/migrate", { method: "POST" }); showToast("数据库迁移已执行"); await Promise.all([checkMigration(), loadTables()]); } catch (error) { handleError(error); } };
const saveTableJson = async () => { if (!selectedTable.value) return; try { const data = JSON.parse(tableJson.value); if (!Array.isArray(data)) throw new Error("数据必须是 JSON 数组"); await apiJson(`/dba/db-tables/${encodeURIComponent(selectedTable.value)}`, { method: "PUT", body: jsonBody({ data }) }); showToast("数据表已更新"); await selectTable(selectedTable.value); } catch (error) { handleError(error); } };
const deleteTableRow = async (row: Record<string, unknown>) => { if (!selectedTable.value || !window.confirm("确认删除这条数据？此操作不可撤销。")) return; try { await apiJson(`/dba/db-tables/${encodeURIComponent(selectedTable.value)}`, { method: "DELETE", body: jsonBody({ data: [row] }) }); showToast("记录已删除"); await Promise.all([selectTable(selectedTable.value), loadTables()]); } catch (error) { handleError(error); } };
const truncateTable = async () => { if (!selectedTable.value || !window.confirm(`确认清空数据表 ${selectedTable.value}？这会级联删除关联数据。`)) return; try { await apiJson(`/dba/db-tables/${encodeURIComponent(selectedTable.value)}`, { method: "DELETE", body: jsonBody({ data: "all" }) }); showToast("数据表已清空"); await Promise.all([selectTable(selectedTable.value), loadTables()]); } catch (error) { handleError(error); } };

const updateUser = async (user: AdminUser) => { try { await apiJson(`/admin/users/${user.id}`, { method: "PATCH", body: jsonBody({ role: Number(user.role), disabled: user.disabled }) }); showToast(`已保存 ${user.username} 的权限`); } catch (error) { handleError(error); } };
const deleteUser = async (user: AdminUser) => { if (!window.confirm(`确认删除用户“${user.username}”？该操作不可撤销。`)) return; try { await apiJson(`/admin/users/${user.id}`, { method: "DELETE" }); users.value = users.value.filter((item) => item.id !== user.id); showToast("用户已删除"); } catch (error) { handleError(error); } };
const createUser = async () => { if (!createUsername.value.trim() || createPassword.value.length < 6) { showToast("请输入账户名和至少 6 位密码"); return; } try { await apiJson("/admin/user/create", { method: "POST", body: jsonBody({ username: createUsername.value.trim(), password: await cryptoHash(createPassword.value), role: createRole.value }) }); createUsername.value = ""; createPassword.value = ""; showToast("用户已创建"); await loadUsers(); } catch (error) { handleError(error); } };
const cryptoHash = async (password: string) => { const data = new TextEncoder().encode(`${password}-hello_pkuphysu`); const digest = await crypto.subtle.digest("SHA-256", data); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join(""); };
const deletePost = async (post: ApiPost) => { if (!window.confirm(`确认删除帖子 #${post.id}？其评论也会被删除。`)) return; try { await apiJson(`/admin/forum/posts/${post.id}`, { method: "DELETE" }); posts.value = posts.value.filter((item) => item.id !== post.id); showToast("帖子已删除"); } catch (error) { handleError(error); } };
const deleteComment = async (comment: AdminComment) => { if (!window.confirm(`确认删除评论 #${comment.cid}？`)) return; try { await apiJson(`/admin/forum/comments/${comment.cid}`, { method: "DELETE" }); comments.value = comments.value.filter((item) => item.cid !== comment.cid); showToast("评论已删除"); } catch (error) { handleError(error); } };
const resolveReport = async (report: Report) => { try { await apiJson(`/admin/forum/reports/${report.id}/resolve`, { method: "POST" }); report.status = "resolved"; showToast("举报已处理"); } catch (error) { handleError(error); } };

const getFingerprint = () => { const key = "pkuphysu-wechat-fingerprint"; let value = localStorage.getItem(key); if (!value) { value = (crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`).replace(/[^a-zA-Z0-9_-]/g, ""); localStorage.setItem(key, value); } return value; };
const loadWechatArticles = async () => { try { wechatArticles.value = (await apiJson<WechatArticle[]>("/wechat/posts?limit=100&page=1")).data || []; } catch (error) { handleError(error); } };
const loadWechatExpiry = async () => { try { const result = await (await requestApi("/wechat/check-health")).json() as { expire?: number }; wechatExpiry.value = result.expire ? result.expire * 1000 : null; } catch { wechatExpiry.value = null; } };
const stopQrPolling = () => { if (qrPollTimer) window.clearInterval(qrPollTimer); qrPollTimer = undefined; if (qrcodeUrl.value) { URL.revokeObjectURL(qrcodeUrl.value); qrcodeUrl.value = ""; } };
const checkWechat = async () => {
  stopQrPolling(); wechatStatus.value = "checking"; wechatMessage.value = "正在检查微信公众号登录状态……";
  try { await apiJson("/wechat/"); wechatStatus.value = "valid"; wechatMessage.value = "微信登录状态有效。"; await loadWechatExpiry(); return; } catch { /* Expired cookies start the QR flow below. */ }
  try {
    const fingerprint = getFingerprint(); const qrResponse = await requestApi(`/wechat/scanloginqrcode?action=getqrcode&fingerprint=${encodeURIComponent(fingerprint)}`); if (!qrResponse.ok) throw new Error("二维码获取失败"); const blob = await qrResponse.blob(); qrcodeUrl.value = URL.createObjectURL(blob); wechatStatus.value = "expired"; wechatMessage.value = "请使用微信扫描二维码，页面会自动确认登录。";
    let attempts = 0; qrPollTimer = window.setInterval(async () => { attempts += 1; if (attempts > 120) { stopQrPolling(); wechatMessage.value = "二维码已超时，请重新检查。"; return; } try { const result = await (await requestApi(`/wechat/scanloginqrcode?action=ask&fingerprint=${encodeURIComponent(fingerprint)}`)).json() as { status?: number }; if (result.status === 1) { stopQrPolling(); await apiJson(`/wechat/login?fingerprint=${encodeURIComponent(fingerprint)}`); wechatStatus.value = "valid"; wechatMessage.value = "微信登录成功。"; await loadWechatExpiry(); } } catch (error) { stopQrPolling(); handleError(error); } }, 1000);
  } catch (error) { wechatStatus.value = "unknown"; wechatMessage.value = errorMessage(error); }
};
const updateWechatPosts = async () => { busy.value = true; try { await apiJson("/wechat/update-posts?begin=0&count=10", { method: "POST" }); await loadWechatArticles(); showToast("微信文章已更新"); } catch (error) { handleError(error); } finally { busy.value = false; } };

const loadPage = async (path: string) => { try { if (path === "/console/users") await loadUsers(); else if (path === "/console/content/posts") await loadPosts(); else if (path === "/console/content/comments") { if (!posts.value.length) await loadPosts(); if (selectedCommentPostId.value === null) selectedCommentPostId.value = posts.value[0]?.id ?? null; await loadComments(); } else if (path === "/console/content/articles") await loadArticles(); else if (path === "/console/content/reports") await loadReports(); else if (path === "/console/database/tables") await loadTables(); else if (path === "/console/database/migrations") await checkMigration(); else if (path === "/console/wechat") { await Promise.all([loadWechatArticles(), loadWechatExpiry()]); } } catch (error) { handleError(error); } };

watch(selectedCommentPostId, () => { if (currentPath.value === "/console/content/comments") void loadComments(); });
onMounted(async () => {
  window.addEventListener("keydown", onKeydown); window.addEventListener("popstate", onPopstate);
  try { const result = await apiJson<BackendUser>("/user/me"); currentUser.value = result.data; if (result.data.role !== 2) { window.location.replace("/"); return; } await loadPage(currentPath.value); }
  catch (error) { if (error instanceof ApiError && error.status === 401) clearAuthSession(); window.location.replace(`/login?next=${encodeURIComponent(window.location.pathname)}`); handleError(error); }
  if (currentUser.value?.role === 2) document.body.classList.add("console-auth-ready");
});
onBeforeUnmount(() => { window.removeEventListener("keydown", onKeydown); window.removeEventListener("popstate", onPopstate); window.clearTimeout(toastTimer); stopQrPolling(); document.body.classList.remove("console-auth-ready"); });
</script>

<template>
  <div class="console-app" :class="{ 'console-sidebar-open': sidebarOpen }">
    <div class="console-mobile-header"><a class="console-brand" href="/"><span class="console-brand__mark"><img src="/assets/PKU.svg" alt="" /></span><span><strong>PKUPHYSU</strong><small>控制台</small></span></a><button class="console-icon-button" type="button" :aria-expanded="sidebarOpen" aria-label="打开控制台导航" @click="sidebarOpen = !sidebarOpen"><Icon name="menu" :size="20" /></button></div>
    <aside class="console-sidebar" aria-label="控制台导航"><div class="console-sidebar__brand"><a class="console-brand" href="/"><span class="console-brand__mark"><img src="/assets/PKU.svg" alt="" /></span><span><strong>PKUPHYSU</strong><small>学生会控制台</small></span></a></div><button class="console-search" type="button" aria-label="打开命令搜索" @click="openPalette"><Icon name="search" :size="16" /><span>搜索页面</span><kbd>Ctrl K</kbd></button><div class="console-sidebar__scroll"><nav class="console-nav"><div v-for="(group, groupIndex) in consoleNavGroups" :key="groupKey(group.label, groupIndex)" class="console-nav-group"><button v-if="group.label" class="console-nav-label console-nav-label--button" type="button" @click="toggleGroup(groupKey(group.label, groupIndex))"><span>{{ group.label }}</span><Icon name="chevron" :size="15" :class="{ 'is-rotated': collapsedGroups[groupKey(group.label, groupIndex)] }" /></button><div v-show="!group.label || !collapsedGroups[groupKey(group.label, groupIndex)]"><a v-for="item in group.items" :key="item.path" :href="item.path" :class="{ active: item.path === currentPath }" @click.prevent="navigate(item.path)"><Icon :name="item.icon" :size="17" /><span>{{ item.label }}</span><b v-if="item.badge">{{ item.badge }}</b></a></div></div></nav></div><div class="console-profile"><div class="console-profile__avatar">{{ getInitials(currentUser?.username || "A").slice(0, 1) }}</div><div><strong>{{ currentUser?.username || "当前用户" }}</strong><span>{{ roleLabel(currentUser?.role) }}</span></div><a class="console-icon-button" href="/usr" aria-label="打开个人中心"><Icon name="arrow-up-right" :size="17" /></a></div></aside>
    <div v-if="sidebarOpen" class="console-sidebar-scrim" aria-hidden="true" @click="sidebarOpen = false"></div>
    <main class="console-main"><header class="console-topbar"><div class="console-breadcrumb"><span>PKUPHYSU</span><i>/</i><strong>{{ currentItem.label }}</strong></div><div class="console-topbar__actions"><button class="console-top-action" type="button" @click="openPalette"><Icon name="search" :size="16" /><span>快速搜索</span><kbd>Ctrl K</kbd></button><a class="console-top-action console-top-action--home" href="/">返回前台 <Icon name="arrow-up-right" :size="15" /></a></div></header>
      <section v-if="currentPath === '/console' || currentPath === '/console/dashboard'" class="console-page"><div class="console-page-header"><div><div class="console-page-title"><span class="console-title-icon"><Icon name="grid" :size="18" /></span><h1>总览</h1></div><p>欢迎回来，这里是内容空间的状态摘要。</p></div><button class="console-secondary-button" type="button" @click="designerOpen = true"><Icon name="settings" :size="16" />布局设置</button></div><div class="console-dashboard-grid"><article v-for="stat in consoleStats" :key="stat.label" class="console-widget console-stat-widget" :class="`console-stat-widget--${stat.tone}`"><div class="console-widget__head"><span>{{ stat.label }}</span><Icon :name="stat.icon" :size="18" /></div><strong>{{ stat.value }}</strong><small>{{ stat.delta }} <span>较上月</span></small></article><article class="console-widget console-widget--wide"><div class="console-widget__head"><div><span>近期活动</span><strong>系统摘要</strong></div><button class="console-more" type="button" @click="showToast('总览暂时保留 mock 数据')"><Icon name="more" :size="18" /></button></div><div class="console-activity-list"><div><span class="console-activity-dot console-activity-dot--blue"></span><p><strong>后端管理 API 已接入</strong><small>用户、帖子、评论与数据库模块可操作</small></p><time>现在</time></div><div><span class="console-activity-dot console-activity-dot--green"></span><p><strong>总览指标仍为 mock</strong><small>等待专用统计接口</small></p><time>本阶段</time></div></div></article><article class="console-widget"><div class="console-widget__head"><span>快捷操作</span><Icon name="plus" :size="18" /></div><div class="console-quick-actions"><button type="button" @click="navigate('/console/users')">用户权限</button><button type="button" @click="navigate('/console/content/posts')">管理帖子</button><button type="button" @click="navigate('/console/database/tables')">打开数据库</button></div></article><article class="console-widget"><div class="console-widget__head"><span>系统状态</span><Icon name="check" :size="18" /></div><div class="console-system-status"><span class="status-dot"></span><strong>API 协同模式</strong><small>总览指标待后端接口</small></div></article></div></section>

      <section v-else class="console-page console-data-page"><div class="console-page-header"><div><div class="console-page-title"><span class="console-title-icon"><Icon :name="currentItem.icon" :size="18" /></span><h1>{{ currentItem.label }}</h1></div><p>此模块已连接后端接口，操作会写入测试数据库。</p></div><span class="console-api-status"><span class="status-dot"></span>API CONNECTED</span></div>
        <div v-if="currentPath === '/console/users'" class="console-data-card"><div class="console-toolbar"><div><strong>用户权限管理</strong><span>{{ users.length }} 个账户</span></div><div class="console-form-inline"><input v-model="createUsername" placeholder="新账户名" /><input v-model="createPassword" type="password" placeholder="初始密码" /><select v-model.number="createRole"><option :value="0">普通用户</option><option :value="1">成员</option><option :value="2">管理员</option></select><button class="console-primary-button" type="button" @click="createUser">创建用户</button></div></div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>ID</th><th>账户</th><th>学号</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td>{{ user.id }}</td><td><strong>{{ user.username }}</strong><small>{{ user.bio || "暂无简介" }}</small></td><td>{{ user.stuid || "—" }}</td><td><select v-model.number="user.role"><option :value="0">普通用户</option><option :value="1">成员</option><option :value="2">管理员</option></select></td><td><label class="console-check"><input v-model="user.disabled" type="checkbox" />禁用</label></td><td><button class="console-text-button" type="button" @click="updateUser(user)">保存</button><button class="console-text-button console-danger" type="button" @click="deleteUser(user)">删除</button></td></tr><tr v-if="!users.length"><td colspan="6" class="console-empty-cell">暂无用户数据</td></tr></tbody></table></div></div>
        <div v-else-if="currentPath === '/console/content/posts'" class="console-data-card"><div class="console-toolbar"><div><strong>论坛帖子</strong><span>管理员可删除违规内容</span></div><button class="console-secondary-button" type="button" @click="loadPosts">刷新</button></div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>ID</th><th>内容</th><th>作者</th><th>互动</th><th>时间</th><th>操作</th></tr></thead><tbody><tr v-for="post in posts" :key="post.id"><td>#{{ post.id }}</td><td><strong>{{ post.text.replace(/<[^>]*>/g, '').slice(0, 70) || '空内容' }}</strong><small>{{ (post.tags || []).join(' · ') }}</small></td><td>{{ post.username }}</td><td>{{ post.reply }} 评论 · {{ post.likenum }} 赞</td><td>{{ displayTime(post.timestamp) }}</td><td><button class="console-text-button console-danger" type="button" @click="deletePost(post)">删除帖子</button></td></tr><tr v-if="!posts.length"><td colspan="6" class="console-empty-cell">暂无帖子数据</td></tr></tbody></table></div></div>
        <div v-else-if="currentPath === '/console/content/comments'" class="console-data-card"><div class="console-toolbar"><div><strong>论坛评论</strong><span>选择帖子查看其评论</span></div><select v-model.number="selectedCommentPostId" class="console-select"><option :value="null">选择帖子</option><option v-for="post in posts" :key="post.id" :value="post.id">#{{ post.id }} · {{ post.username }}</option></select></div><div v-if="selectedCommentPost" class="console-context">当前帖子：#{{ selectedCommentPost.id }} {{ selectedCommentPost.text.replace(/<[^>]*>/g, '').slice(0, 100) }}</div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>ID</th><th>评论</th><th>作者</th><th>点赞</th><th>时间</th><th>操作</th></tr></thead><tbody><tr v-for="comment in comments" :key="comment.cid"><td>#{{ comment.cid }}</td><td>{{ comment.text.replace(/<[^>]*>/g, '').slice(0, 100) }}</td><td>{{ comment.username }}</td><td>{{ comment.likenum }}</td><td>{{ displayTime(comment.timestamp) }}</td><td><button class="console-text-button console-danger" type="button" @click="deleteComment(comment)">删除</button></td></tr><tr v-if="!comments.length"><td colspan="6" class="console-empty-cell">请选择有评论的帖子</td></tr></tbody></table></div></div>
        <div v-else-if="currentPath === '/console/content/articles'" class="console-data-card"><div class="console-toolbar"><div><strong>文章</strong><span>来自 WeChat 文章接口</span></div><button class="console-secondary-button" type="button" @click="loadArticles">刷新</button></div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>标题</th><th>分类</th><th>发布时间</th><th>来源</th><th>链接</th></tr></thead><tbody><tr v-for="article in articles" :key="article.id"><td><strong>{{ article.title }}</strong><small>{{ article.description }}</small></td><td>{{ article.tag }}</td><td>{{ article.publish_time }}</td><td>{{ article.mp_name }}</td><td><a class="console-text-button" :href="article.url" target="_blank" rel="noreferrer">打开</a></td></tr><tr v-if="!articles.length"><td colspan="5" class="console-empty-cell">暂无文章数据</td></tr></tbody></table></div></div>
        <div v-else-if="currentPath === '/console/content/reports'" class="console-data-card"><div class="console-toolbar"><div><strong>举报</strong><span>处理论坛内容举报</span></div><button class="console-secondary-button" type="button" @click="loadReports">刷新</button></div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>ID</th><th>对象</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="report in reports" :key="report.id"><td>#{{ report.id }}</td><td>{{ report.post_id ? `帖子 #${report.post_id}` : report.comment_id ? `评论 #${report.comment_id}` : "—" }}</td><td>{{ report.reason || "—" }}</td><td>{{ report.status || "待处理" }}</td><td><button class="console-text-button" type="button" @click="resolveReport(report)">标记已处理</button></td></tr><tr v-if="!reports.length"><td colspan="5" class="console-empty-cell">暂无举报数据</td></tr></tbody></table></div></div>
        <div v-else-if="currentPath === '/console/database/tables'" class="console-db-layout"><aside class="console-db-tables console-data-card"><div class="console-toolbar"><div><strong>模型数据表</strong><span>{{ tables.length }} 个数据模型</span></div><button class="console-secondary-button console-compact-button" type="button" @click="loadTables"><Icon name="refresh" :size="15" />刷新</button></div><div class="console-db-table-list"><button v-for="table in tables" :key="table.name" class="console-db-table-button" :class="{ active: selectedTable === table.name }" type="button" @click="selectTable(table.name)"><span><strong>{{ table.name }}</strong><small>{{ table.info.description || table.info.model }}</small></span><b>{{ table.info.exists ? table.info.rows : "未创建" }}</b></button></div></aside><section class="console-data-card console-db-detail"><div class="console-toolbar console-db-toolbar"><div><strong>{{ selectedTable || "选择数据表" }}</strong><span>{{ tableData?.count ?? 0 }} 条记录 · {{ tableData?.columns?.length ?? 0 }} 列</span></div><div class="console-toolbar__actions"><button class="console-secondary-button" type="button" @click="saveTableJson"><Icon name="check" :size="15" />保存 JSON</button><button class="console-secondary-button console-danger-button" type="button" @click="truncateTable">清空表</button></div></div><div class="console-db-editor"><div class="console-db-section-heading"><div><strong>JSON 编辑器</strong><span>直接编辑当前表的记录数组</span></div><code>{{ selectedTable || "—" }}</code></div><textarea v-model="tableJson" class="console-json-editor" spellcheck="false" aria-label="数据表 JSON 编辑器"></textarea></div><div class="console-db-preview"><div class="console-db-section-heading"><div><strong>数据预览</strong><span>宽表可在下方区域横向滚动</span></div><span v-if="tableData">{{ tableRows.length }} ROWS</span></div><div class="console-table-wrap console-db-table-wrap"><table v-if="tableData" class="console-table console-db-table"><thead><tr><th v-for="column in tableData.columns" :key="column">{{ column }}</th><th>操作</th></tr></thead><tbody><tr v-for="(row, index) in tableRows" :key="index"><td v-for="column in tableData.columns" :key="column" :title="displayCell(row[column])">{{ displayCell(row[column]) }}</td><td><button class="console-text-button console-danger" type="button" @click="deleteTableRow(row)">删除</button></td></tr></tbody></table><p v-else class="console-empty-cell">选择左侧数据表开始检查。</p></div></div></section></div>
        <div v-else-if="currentPath === '/console/database/migrations'" class="console-data-card"><div class="console-toolbar"><div><strong>数据库迁移</strong><span>{{ migrationState }}</span></div><div><button class="console-secondary-button" type="button" @click="checkMigration">检查</button><button class="console-primary-button" type="button" @click="executeMigration">执行迁移</button></div></div><ul class="console-migration-list"><li v-for="item in migration" :key="item">{{ item }}</li><li v-if="!migration.length">暂无迁移结果，请点击检查。</li></ul></div>
        <div v-else-if="currentPath === '/console/wechat'" class="console-data-card console-wechat-page"><div class="console-toolbar"><div><strong>WeChat 扫码爬文</strong><span>调用后端微信公众号登录与文章抓取能力</span></div><div><button class="console-secondary-button" type="button" :disabled="wechatStatus === 'checking'" @click="checkWechat">{{ wechatStatus === 'valid' ? '检查登录' : '扫码登录' }}</button><button class="console-primary-button" type="button" :disabled="busy" @click="updateWechatPosts">{{ busy ? '更新中……' : '更新文章' }}</button></div></div><div class="console-wechat-status"><div class="console-wechat-status__badge" :class="`is-${wechatStatus}`"><span class="status-dot"></span>{{ wechatStatus === 'valid' ? '已登录' : wechatStatus === 'checking' ? '检查中' : '需要扫码登录' }}</div><p>{{ wechatMessage || '点击扫码登录检查后端保存的 Cookie。' }}</p><small v-if="wechatExpiry">Cookie 有效期至 {{ new Date(wechatExpiry).toLocaleString('zh-CN') }}</small></div><div v-if="qrcodeUrl" class="console-qrcode"><img :src="qrcodeUrl" alt="微信登录二维码" /><p>请使用微信扫描二维码</p></div><div class="console-table-wrap"><table class="console-table"><thead><tr><th>标题</th><th>标签</th><th>发布时间</th><th>链接</th></tr></thead><tbody><tr v-for="article in wechatArticles" :key="article.id"><td><strong>{{ article.title }}</strong><small>{{ article.description }}</small></td><td>{{ article.tag }}</td><td>{{ article.publish_time }}</td><td><a class="console-text-button" :href="article.url" target="_blank" rel="noreferrer">打开</a></td></tr><tr v-if="!wechatArticles.length"><td colspan="4" class="console-empty-cell">暂无已抓取文章</td></tr></tbody></table></div></div>
        <div v-else class="console-placeholder-card console-data-card"><span class="console-placeholder-card__icon"><Icon name="settings" :size="22" /></span><h2>{{ currentItem.label }}</h2><p>此功能暂无对应后端 API，保留控制台入口。</p></div>
      </section>
    </main>
    <div v-if="paletteOpen" class="console-dialog-backdrop" @click.self="closePalette"><section class="console-palette" role="dialog" aria-modal="true" aria-label="搜索控制台页面"><div class="console-palette__input"><Icon name="search" :size="18" /><input ref="paletteInput" v-model="paletteQuery" placeholder="搜索页面……" /></div><div class="console-palette__items"><button v-for="item in paletteItems" :key="item.path" type="button" @click="navigate(item.path); closePalette()"><Icon :name="item.icon" :size="17" /><span>{{ item.label }}</span><small>{{ item.path }}</small></button><p v-if="!paletteItems.length">没有匹配页面</p></div></section></div>
    <div v-if="designerOpen" class="console-dialog-backdrop" @click.self="designerOpen = false"><section class="console-designer" role="dialog" aria-modal="true"><div class="console-designer__head"><div><p class="eyebrow">DASHBOARD</p><h2>布局设置</h2></div><button class="console-icon-button" type="button" aria-label="关闭" @click="designerOpen = false"><Icon name="close" :size="18" /></button></div><p>总览暂时使用 mock 指标，布局配置将在统计 API 接入后开放。</p><button class="console-primary-button" type="button" @click="designerOpen = false">知道了</button></section></div>
    <Transition name="toast"><div v-if="toast" class="console-toast" role="status">{{ toast }}</div></Transition>
  </div>
</template>
